services:
  - type: web
    name: my-fullstack-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false   # 👈 means you’ll set this value manually in the Render dashboard
